### PR TITLE
libtensorflow and libtensorflow_cc

### PR DESCRIPTION
**Pull request by njzjz**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

try to replace conda-forge/staged-recipes#9117

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
@hajapy Now it works well in `linux_python3.6` and `linux_python3.7`, but exceeds the limit CI time (360 minutes) in  `linux_python2.7`. The time seems not enough. Is it better to separate C/C++ from Python?

**Comment by hajapy** [comment]
Given how close https://github.com/conda-forge/tensorflow-feedstock/pull/78 is to working and how much it reduces the build time, I’d be inclined to see if we can stack your changes on top of that branch and get all the Linux builds passing (only OS X seems to be remaining challenge).

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
> Given how close #78 is to working and how much it reduces the build time, I’d be inclined to see if we can stack your changes on top of that branch and get all the Linux builds passing (only OS X seems to be remaining challenge).

I have merged #78 into my branch. Wait for the CI.

**Comment by njzjz** [comment]
Caught this error:
```
bazel-out/k8-opt/bin/external/com_google_absl/absl/time/_objs/time/clock.pic.o:clock.cc:function absl::GetCurrentTimeNanosSlowPath(): error: undefined reference to 'clock_gettime'
bazel-out/k8-opt/bin/external/grpc/_objs/gpr_base/time_posix.pic.o:time_posix.cc:function now_impl(gpr_clock_type): error: undefined reference to 'clock_gettime'
bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/attention_ops/attention_ops.pic.o:attention_ops.cc:function void Eigen::(anonymous namespace)::GlimpseExtractionOp<long>::eval<Eigen::TensorLayoutSwapOp<Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const>, Eigen::TensorMap<Eigen::Tensor<float, 4, 0, long>, 0, Eigen::MakePointer>, Eigen::ThreadPoolDevice>(Eigen::TensorLayoutSwapOp<Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const&, Eigen::TensorMap<Eigen::Tensor<float, 4, 0, long>, 0, Eigen::MakePointer>&, Eigen::ThreadPoolDevice const&) const: error: undefined reference to 'clock_gettime'
bazel-out/k8-opt/bin/tensorflow/core/kernels/_objs/attention_ops/attention_ops.pic.o:attention_ops.cc:function void Eigen::(anonymous namespace)::GlimpseExtractionOp<long>::eval<Eigen::TensorLayoutSwapOp<Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const>, Eigen::TensorMap<Eigen::Tensor<float, 4, 0, long>, 0, Eigen::MakePointer>, Eigen::ThreadPoolDevice>(Eigen::TensorLayoutSwapOp<Eigen::TensorMap<Eigen::Tensor<float const, 4, 1, long>, 16, Eigen::MakePointer> const> const&, Eigen::TensorMap<Eigen::Tensor<float, 4, 0, long>, 0, Eigen::MakePointer>&, Eigen::ThreadPoolDevice const&) const: error: undefined reference to 'clock_gettime'
collect2: error: ld returned 1 exit status
```

**Comment by njzjz** [comment]
> Given how close #78 is to working and how much it reduces the build time, I’d be inclined to see if we can stack your changes on top of that branch and get all the Linux builds passing (only OS X seems to be remaining challenge).

Ok all Linux builds passed, but what about OS X?

**Comment by njzjz** [comment]
I revert osx builds in #80. If the problem cannot be solved in a short time, maybe #80 is a choice.

**Comment by hajapy** [comment]
That the Linux build works is a great thing! Good work. Consider adding yourself to maintainer list.

For the OS X issue, seems like we are missing some linking trick? 

Maybe useful:
https://github.com/tensorflow/tensorflow/issues/15129

**Comment by njzjz** [comment]
> That the Linux build works is a great thing! Good work. Consider adding yourself to maintainer list.
> 
> For the OS X issue, seems like we are missing some linking trick?
> 
> Maybe useful:
> [tensorflow/tensorflow#15129](https://github.com/tensorflow/tensorflow/issues/15129)

I have added myself to the list.

The `clock_gettime` appeared in Linux builds and I have fixed it in https://github.com/conda-forge/tensorflow-feedstock/pull/79/commits/79b6cb26670be0f6c879f62ee2f5804ee55b713c. The OSX error is below:
```
[0 / 3] [-----] BazelWorkspaceStatusAction stable-status.txt
ERROR: /private/var/tmp/_bazel_vsts/cc1481791bfddbb5c58e9021e854d45e/external/swig/BUILD.bazel:5:1: undeclared inclusion(s) in rule '@swig//:swig':
this rule is missing dependency declarations for the following files included by 'external/swig/Source/Swig/deprecate.c':
  '/usr/local/miniconda/conda-bld/tensorflow_1566059328055/_build_env/lib/clang/8.0.0/include/stdint.h'
  '/usr/local/miniconda/conda-bld/tensorflow_1566059328055/_build_env/lib/clang/8.0.0/include/stdarg.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
