### PR TITLE
WIP: Tensorflow 2.7.1 Libprotobuf3.20 icu70

### PR DESCRIPTION
**Pull request by hmaarrfk**
Closes https://github.com/conda-forge/tensorflow-feedstock/pull/217

Seems like the grpc upgrade will take more work.

- [x] Update to 2.7.1 Once CPU builds pass.
- [x] Try to use flatbuffers 2.0.5 https://github.com/conda-forge/flatbuffers-feedstock/issues/25
- [ ] Try building with bazel 5+ `export TF_IGNORE_MAX_BAZEL_VERSION=1` [gentoo](https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/tensorflow/tensorflow-2.8.0.ebuild#n308)
- [ ] Unpin compilers for OSX
- [ ] Unpin compilers for Linux
- [ ] Try adding `--jobs ${CPU_COUNT}` to the `BUILD_OPTS` to limit the number of parallel builds.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Compilation TODOs:
* [ ] CPU Builds on Linux
* [ ] GPU Build with 11.0+ on Linux
* [ ] Drop GPU Builds 10.2 on linux (c++17 compatibility?)
* [ ] CPU Builds on OSX amd64
* [ ] CPU Builds on OSX arm

### CODE REVIEW

**Comment by hmaarrfk** [comment]
Notes to self:
```
Execution platform: @local_execution_config_platform//:platform
tensorflow/core/framework/tensor.cc: In static member function 'static const int64_t* tensorflow::{anonymous}::ProtoHelper<long int>::Begin(const tensorflow::TensorProto&)':
tensorflow/core/framework/tensor.cc:344:70: error: invalid cast from type 'google::protobuf::RepeatedField<long int>::const_iterator' {aka 'google::protobuf::internal::RepeatedIterator<const long int>'} to type 'const int64_t*' {aka 'const long int*'}
  344 |     return reinterpret_cast<const int64_t*>(proto.int64_val().begin());
      |                                                                      ^
tensorflow/core/framework/tensor.cc: In static member function 'static const uint64* tensorflow::{anonymous}::ProtoHelper<long unsigned int>::Begin(const tensorflow::TensorProto&)':
tensorflow/core/framework/tensor.cc:358:70: error: invalid cast from type 'google::protobuf::RepeatedField<long unsigned int>::const_iterator' {aka 'google::protobuf::internal::RepeatedIterator<const long unsigned int>'} to type 'const uint64*' {aka 'const long unsigned int*'}
  358 |     return reinterpret_cast<const uint64*>(proto.uint64_val().begin());
```

**Comment by hmaarrfk** [comment]
@xhochy @183amir could one of you build OSX bulids? I have started the linux + cuda bulids locally.

**Comment by hmaarrfk** [comment]
I somehow got stuck at the same point these people did:
https://bugs.gentoo.org/832760#c4

Seems like for newer grpc tensorflow 2.8.0 might be necessary.

A few logs attached for convenience.

[linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562668/linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt)
[linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.21python3.10.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562670/linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.21python3.10.____cpython-log.txt)
[linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.7.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562671/linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.7.____cpython-log.txt)
[linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562672/linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt)

**Comment by hmaarrfk** [comment]
Maybe tensorflow is vendering absl, and so is our version of grpc:
https://github.com/tensorflow/tensorflow/issues/53317#issuecomment-988102065

I'm not sure, just keeping tabs of notes I find.

**Comment by ngam** [comment]
> Maybe tensorflow is vendering absl, and so is our version of grpc: [tensorflow/tensorflow#53317 (comment)](https://github.com/tensorflow/tensorflow/issues/53317#issuecomment-988102065)
> 
> I'm not sure, just keeping tabs of notes I find.

> I somehow got stuck at the same point these people did: https://bugs.gentoo.org/832760#c4
> 
> Seems like for newer grpc tensorflow 2.8.0 might be necessary.
> 
> A few logs attached for convenience.
> 
> [linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562668/linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt) [linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.21python3.10.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562670/linux_64_c_compiler_version9cuda_compiler_version11.1cudnn8cxx_compiler_version9numpy1.21python3.10.____cpython-log.txt) [linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.7.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562671/linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.7.____cpython-log.txt) [linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt](https://github.com/conda-forge/tensorflow-feedstock/files/8562672/linux_64_c_compiler_version9cuda_compiler_version11.2cudnn8cxx_compiler_version9numpy1.19python3.9.____cpython-log.txt)


@hmaarrfk would it make more sense to then try to build 2.8.0 at this stage or do we think 2.7.x is necessary? Feel free to either edit my PR or just rebase it and start over. I am definitely out of my depth here... :(

**Comment by hmaarrfk** [comment]
I just wanted to get pinnings updated. I found a few patches that would help both branches.

Sometimes it is good to divide a problem.

I pushed to your branch on something I felt was a sure fix. The other patches need a bit more work, but, i think we can consolidate at some point.

If you can confirm that GPU builds locally that would be great. I got close to building the python stuff then GPU failed.

**Comment by hmaarrfk** [comment]
I'm going to have to:

1.  rebuild the newer grpc with the older absl and specify the absl version here
2. Update the absl related files inside tensorflow (not sure which those are).

**Comment by ngam** [comment]
> If you can confirm that GPU builds locally that would be great

To confirm, build the other PR, right? I will get some allocation to test this later today. I will post the build error here (if any). Also, fwiw, I tried building xhochy's branch without docker (i.e. on an hpc with all modules purged) and it failed with some nonsensical errors. Do you still build according to the readme (i.e. 10 cpus, etc. — approx. how much storage and memory do you think should be enough?)



> could one of you build OSX bulids?

I could build the osx-arm64 ones pretty easily (I recently got rid of my osx-64 machine, but I still could build that too), so just let me know when ready

**Comment by ngam** [comment]
> Sometimes it is good to divide a problem

Yes, I agree. I misunderstood your comments — I thought you were patching stuff to includes update from 2.8.0 and 2.9.0. But I am all for building all of them step by step (2.7.1, 2.8.0, 2.8.1, and 2.9.0).

**Comment by hmaarrfk** [comment]
I don't need to build step by step, but you had some strange failures, that I was able to debug by taking a step back, I'll circle back to this this weekend.

**Comment by h-vetinari** [comment]
> I'm going to have to:
>  1. rebuild the newer grpc with the older absl and specify the absl version here
>  2. Update the absl related files inside tensorflow (not sure which those are).

What problems did you run into? Note that abseil has an ABI-dependence on the C++ standard version used to compile it, and we're not providing all versions currently (e.g. if tensorflow expects the C++14 ABI it won't work unless we tackle https://github.com/conda-forge/abseil-cpp-feedstock/issues/29)

**Comment by hmaarrfk** [comment]
The two patches for libprotobuf

**Comment by hmaarrfk** [comment]
@h-vetinari is there a way to specify c++ with bazel. I can't seem to figure it out...

**Comment by hmaarrfk** [comment]
@h-vetinari is there a way to specify c++ with bazel. I can't seem to figure it out...

**Comment by h-vetinari** [comment]
> @h-vetinari is there a way to specify c++ with bazel. I can't seem to figure it out...

Sorry, I don't have the bazel-fu for that either. Would likewise need to google / dig. Maybe @xhochy knows?

**Comment by xhochy** [comment]
Tensorflow is not compatible with C++17, we should keep using C++14. There is a way to change that but I tried and failed.

**Comment by h-vetinari** [comment]
> Tensorflow is not compatible with C++17, we should keep using C++14. There is a way to change that but I tried and failed.

Thanks for the info. Could you maybe chime in in https://github.com/conda-forge/abseil-cpp-feedstock/issues/29? Seems relevant, because currently we're building grpc-cpp in a way that requires C++17 (through abseil being a host-dep in grpc + its run-export as well as ABI-sensitivity to cxx std).

**Comment by h-vetinari** [comment]
> Seems relevant, because currently we're building grpc-cpp in a way that requires C++17

Sorry, got mixed up with grpc & protobuf. I think the point is still relevant though.

**Comment by hmaarrfk** [comment]
@xhochy i really am willing to try and back port patches if you can point me in the right direction with the build options for bazel.

The issue is that without this, I'm forced to rebuild my stack with the last protobuf we built tensorflow for, which is really causing update issues with mamba.

**Comment by hmaarrfk** [comment]
Well fingers crossed!

**Comment by hmaarrfk** [comment]
> Happy to contribute patches but I'm struggling to understand all the modifications done in this PR. Should we first attempt libprotobuf319 maybe? I'm happy to build stuff in this and the next week (was a bit off in the last 2-3 weeks).

We can try to build icu70 + 1.7.1.

I think that would be worthwhile and reduce the amount of compiler changes.
